### PR TITLE
pass empty string instead of nil for empty site baseurl

### PR DESCRIPTION
**Pull request by rbuchberger**
#65 

Edit: linked the wrong issue. See delucis' comment below

### CODE REVIEW

**Comment by delucis** [comment]
See also #85 and #83

**Comment by rbuchberger** [comment]
Has there been any word from robwierzbowski on this repo in awhile? Last activity was 3 years ago. He looks to be active on github, but only in private repos.

**Comment by delucis** [comment]
Don’t think so, I’ve been using a personal fork for a while.

**Comment by rbuchberger** [comment]
Yeah, I'm working from my own fork as well. I was hoping a new PR would wake him up!

**Pull request merged**
